### ISSUE TITLE
Add POST and PUT requests to API Wrapper module

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-js#33]
Like sendLSK, addSecondSignature etc

**Comment by karmacoma** [comment]
Closing due to planned API redesign in Lisk Core: https://github.com/LiskHQ/lisk/issues/225. This redesign will result in a single `POST /api/transactions` endpoint. Therefore, no need to add any support for the existing `PUT`, `POST` endpoints. They are scheduled for removal here: https://github.com/LiskHQ/lisk/issues/457
