### ISSUE TITLE
Change of behavior when creating vote transactions

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-js#625]
### Description
Previous behavior:
```
transaction = elements.vote.createVote(
	'bla bla bla',
	['-delegate1', '+delegate2']
);
```
Results with following:
```
['-delegate1', '+delegate2']
```

Current behavior:
```
transaction = elements.transaction.castVotes({
	passphrase: 'bla bla bla',
	unvotes: ['delegate1'],
	votes: ['delegate2'],
});
```
Results with following:
```
['+delegate2', '-delegate1']
```
There is not possible to change the order, so it will not be possible to recreate transactions created by previous version of Lisk Elements. Is that behavior expected?

### Steps to Reproduce
Run Lisk Core 1.0.0 functional system rounds tests. ;)

**Expected behavior:** N/A

**Actual behavior:** N/A

**Reproduces how often:** 100%

### Versions
`lisk-elements-1.0.0-RC2` @ Node.js

### Additional Information
N/A

**Comment by Tosch110** [comment]
Thanks @4miners for submitting this. Even though I am in favor of maintaining the new functionality, so that users do not have to deal with internal syntax for voting (adding `+` or `-` to public keys). They can add the `votes` and `unvotes` as public keys they can find in the explorer etc. 

If you would like to create the exact same transaction as before with the same signature you should be using the same software version as before.
