### ISSUE TITLE
Make signData function more atomic

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisk-js#626]
### Description
I propose to move `getPrivateAndPublicKeyBytesFromPassphrase` out from `signData` function, and pass `privateKey` dircetrly to the `signData` function instead of `passphrase`. Like in `verifyData` which expects `publicKey` instead of passphrase. 

**Expected behavior:**
`signData` expect `data` and `privateKey ` as parameters

**Actual behavior:**
`signData` expect `data` and `passphrase ` as parameters

**Reproduces how often:**
Always

### Versions
`lisk-js 1.0.0`

**Comment by willclarktech** [comment]
I'm not sure this is purely a question of atomicity, it's more a question of what we want to support our users in doing. One of the aims of this product is to simplify things, so people don't need to make decisions about how to use cryptography. If there's a significant group of users who need to be able to use private keys directly, then that's a good argument to split this functionality (and maybe provide two functions instead of one), but I'm not sure how much demand there is for this. To get the ball rolling, what's your use case @alepop?

`verifyData` doesn't need a passphrase, so I don't understand that point. We could use `address` instead of `publicKey` to be more consistent with `signData` in terms of preferring usability, but that would obviously come with a security cost.

**Comment by alepop** [comment]
@willclarktech `If there's a significant group of users who need to be able to use private keys directly, then that's a good argument to split this functionality`. Because of this. I use `lisk-js` in https://github.com/lisk-builders/lisk-hd-key and I need this low level of functionality (in the new version). Of course, I can use `jsnacl ` directly, but I want to use only `lisk-js` public methods.

**Comment by willclarktech** [comment]
I'd actually be in favour of the two functions approach. Maybe `signDataWithPrivateKey` and `signDataWithPassphrase` which calls `signDataWithPrivateKey`. `signData` could be preserved as an alias of `signDataWithPassphrase`. What do you think @Tosch110?
