### ISSUE TITLE
const PBKDF2_ITERATIONS = 1e6;

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-js#659]
What's the point of setting this https://github.com/LiskHQ/lisk-js/blob/development/src/cryptography/encrypt.js#L25 as const while it's clearly variable https://github.com/LiskHQ/lisk/blob/development/test/data/config.json#L80

Additionally, what's the point setting that high number of hash iterations? It does takes a while to compute and usually forging toggle is expected to act immediately.

**Comment by willclarktech** [comment]
Hi Karek, thanks for the issue and the PR. I'm guessing you didn't see this? https://github.com/LiskHQ/lisk-js/pull/656

We recently changed the approach here, and implemented the update in Core first. That PR is to align Lisk Elements with the new approach. To answer your questions:

1. *Why `const`?* Going forward, this is a default value, to be used if the number of rounds is not provided by the user. (One of the aims of Lisk Elements is to simplify cryptographic decisions for users if they want help.)
1. *Why such a high number of iterations?* There's a trade off between convenience and security here. Since there's usually only 1 (or close to 1) passphrase to be decrypted at a time, we aimed for a per-passphrase decryption time of around 1 second (although that will vary according to the user's setup), assuming that would be a reasonable amount of time for node operators to wait in exchange for the defence against brute forcing it offers. If you'd like a different number of iterations, you will be able to pass your preferred number as an argument. See https://github.com/LiskHQ/lisk-js/pull/656/files#diff-83ee28f19f1cdec69280434d37c72ac8R107

**Comment by karek314** [comment]
Hi Will,

Thanks for explaining, yes indeed i've missed this PR.

Regarding point 2, i'm not convinced that this level security is needed there, it appears that it's still easier to hack ed25519 rather than average salted aes256.

Closing this issue as mentioned PR covers all doubts.

**Comment by willclarktech** [comment]
> it's still easier to hack ed25519 rather than average salted aes256.

Do you have sources for this?

**Comment by karek314** [comment]
Depends on attack factor, Curve25519 provides 126 bits of security. AES256 key is 256 bits.  But ultimately is think it's more likely that someone will try eventually claim unclaimed account which are way easier now 2^64. Rather than target forging nodes, eventually such attack makes no economic sense, usually forging accounts are not storage accounts and such account (if hacked) can be swiftly unvoted) - No point of conducting such attack whatsoever.
