### ISSUE TITLE
Not able to use library inside html5 web worker

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-js#7]
Lisk JS does not work when required inside of a html5 web worker, affecting any 3rd party integration which rely on them.

**Comment by Tosch110** [comment]
This is still affected. Error:

No secure random number generator found                   app.js:25281

Which is related to

```
try {
  var crypto = require("crypto"),
  randomValueNodeJS = (function() {
    var buf = crypto.randomBytes(4);
      return (buf[0] << 24 | buf[1] << 16 | buf[2] << 8 | buf[3]) >>> 0
   });
   randomValueNodeJS();
   Module.getRandomValue = randomValueNodeJS
} catch (e) {
   throw "No secure random number generator found"
}
```

I am looking into this

**Comment by Tosch110** [comment]
This is not only a problem for us. The web worker does not have access to the window.crypto 

Problem description:
https://github.com/jedisct1/libsodium.js/issues/46
http://stackoverflow.com/questions/13004375/running-window-crypto-getrandomvalues-from-inside-a-web-worker
https://github.com/bitwiseshiftleft/sjcl/issues/91
https://lists.w3.org/Archives/Public/public-webcrypto-comments/2013Jul/0012.html

possible solutions:
https://github.com/snowblindroan/sjcl-webworker-instructive
https://github.com/ekodo/libsodium-worker-test

**Comment by Tosch110** [comment]
The problem is that webworkers do not have access to the dom, where window.crypto is accessible. lisk-js uses the cryptographic functions from the window.crypto.getRandomValues function. There is currently no way to use window.crypto within a webworker or pass it to the webworker. As discussed here:

http://stackoverflow.com/questions/13004375/running-window-crypto-getrandomvalues-from-inside-a-web-worker
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13904769-support-web-crypto-api-inside-a-web-worker
https://lists.w3.org/Archives/Public/public-webcrypto-comments/2013Jul/0011.html

The solution I could think of is using the lisk-js functions before the webworker, then pass in the necessary information to the webworker and let it do its job. Note that only cryptographic functions are not available in the webworker, but it makes whole lisk-js fail at this point.
We hope that webworker get an equivalent window.crypto soon (edited)
